### ISSUE TITLE
Pass through posts

### ISSUE THREAD

**Issue by tlienart** [cormullion/julialangblog#1]
To keep track of the list of posts + things I see

### general (ongoing)

* use of `@def hascode=true` missing in pages with code
* ~~unqualified code blocks introduce a blank line at the top (use of `md2html` probably)~~
* issues with pre-rendering of pages (possibly due to math env declarations isssues)
* ~~could use `hascode=true` in `config` and use `hascode = false` where there isnt given that there's code on most pages. --> yes though it doesn't work atm (should be fixed, that happens when the dictionaries of variables are merged I suppose)~~

### stuff to fix / check (ongoing)

* footnote links

### fixed

* ~~header as links don't work (!!!)~~ now fixed with https://github.com/tlienart/JuDoc.jl/pull/224
* ~~add Julia logo as `.icns`~~
* ~~code styling starts to fail on `2019-08-28-release-process` (???)~~
* ~~code blocks should be julia by default if unqualified (including triple backticks)~~ now fixed with https://github.com/tlienart/JuDoc.jl/pull/226
* ~~plain code blocks need to be stripped (no top empty line)~~ now fixed with https://github.com/tlienart/JuDoc.jl/pull/226
* ~~table immediately after title is not parsed properly~~ now fixed with https://github.com/tlienart/JuDoc.jl/pull/225

### specifics (ongoing)

* [x] 23 July 2019, multithread 
  * ~~CSS for inline code could do with a bit~~
  * ~~(**bug**) header as links don't work~~
  * ~~(**minor**) add Julia logo as `.icns`~~
* [x] 2019-08-28-release-process.html
  * (**bug**) footnote links
  * ~~(**bug**) code styling starts to fail towards the end (?)~~
* [x] 2019-08-06-2019-julia-survey
  * ~~first link is broken (asset link issue)~~
* [x] 2019/07/multithreading-zh-cn
  * ~~unqualified code blocks~~
* [x] 2019-06-18-diffeqbot.html
  * (**note**) images are centered by default, no need for `~~~...style:text-center...` just use `![](...)`. 
  * ~~(**add**) yaml code~~
* [x] 2019-05-31-jsoc19.html
* [x] 2019-05-02-beyond-ml-pipelines-with-mlj.html
  * (**note**) inline styling of the images to get the side by side etc
  * iframe was not `~~~` (still doesn't show but that's probably my privacy stuff blocking autoplay etc, also doesn't show on julia website)
  * useless `&nbsp;` (?)
* [x] 2019-04-04-fluxdiffeq-zh_tw.html
  * (**note**) maths stuff -- left over `[[` and `]]`, remove and ok
  * footnote problem (see above)
* [x] 2019-03-19-debuggers.html
* [x] 2019-02-12-julia-entities.html
* [x] 2019-02-03-light-graphs.html
* [x] 2019-01-18-fluxdiffeq.html
  * ~~(**minor**) plain code blocks may introduce top or bottom empty lines~~

### 2018

* [x] 2018-12-03-ml-language-compiler.html
* [x] 2018-09-12-Pkgtutorial.html
* [x] 2018-09-11-juliacon2018.html
  * yay dollars show fine
* [x] 2018-09-04-julia-community-prizes.html
  * cool pics
* [x] 2018-08-14-GSoC2018-speech-recognition.html
  * omg the ugly math
  * code qualification
* [x] 2018-08-13-adding-newer-features-and-speeding-up-convolutions-in-flux.html
* [x] 2018-08-09-union-splitting.html
* [x] 2018-08-08-one-point-zero.html
* [x] 2018-08-08-one-point-zero-zh_tw.html
* [x] 2018-08-08-one-point-zero-zh_cn.html
  * I think there's a couple of md errors at the bottom
* [x] 2018-08-08-one-point-zero-es.html
* [x] 2018-08-06-GSoC-Final-Summary.html
* [x] 2018-07-08-iterators-in-julia-0.7.html
  * ok apart from **footnotes**
* [x] 2018-06-19-missing.html
  * also footnotes
* [x] 2018-05-11-extensible-broadcast-fusion.html
* [x] 2018-04-01-tetris-and-you.html
* [x] 2018-03-14-pifonts.html
  * you didn't appear as author 😱 
* [x] 2018-02-21-gsoc2018-numfocus.html

### 2017

(only listing the ones for which there's something to say now)

* [x] 12-20 plcn and other variants
   * added javascript to highlight
* [x] hamiltonian jazz
  * maths fixes omg...
* [x] derivative operators
  * same as above
* [x] cudanative
  * footnote stuff

**Comment by cormullion** [comment]
>unqualified code blocks 

Yes I got tired of qualifying those..   :)

**Comment by tlienart** [comment]
The fun part is that I added a local page variable `lang` for all indented code blocks which are not qualified so that they're considered as Julia code. I could do the same for all unqualified triple backtick-ed code blocks too; the only issue is if someone wants to also introduce plain code blocks but I guess this can be documented easily.

**Comment by cormullion** [comment]
Doesn’t Documenter default to Julia as well... perhaps it’s an expected behaviour. 😀

**Comment by tlienart** [comment]
Ok I've still got quite a few to go through but this is super helpful to quickly get a list of small things to fix, thanks so much for putting the time into this!

**Comment by tlienart** [comment]
Ok I've now gone through all blog posts until 2018 and fixed a bunch of things along the way the one remaining issue I haven't looked at yet is handling footnotes.

Also one thing that was missing in a bunch of the translation was `@def hascode = true` apart from that 👍

**Comment by tlienart** [comment]
cool done everything now and fixed a few things along the way, thanks again so much for doing the heavy lifting in this! super helpful

**Comment by cormullion** [comment]
Awesome stuff! i think it looks pretty good now... essily as good as the official version. :)

**Comment by tlienart** [comment]
And now footnotes work 🎉 

https://julialangblogmirror.netlify.com/pub/2019-08-28-release-process.html#fndef:1

**Comment by cormullion** [comment]
They look great! Playing with CSS is such a good time sink... :)
