### ISSUE TITLE
A few remaining glitches in link conversion

### ISSUE THREAD

**Issue by cormullion** [cormullion/julialangblog#4]
Hi Thibaut! I noticed a couple of glitches in the current processing of the pages.

1: In [extensible broadcast fusion](https://raw.githubusercontent.com/JuliaLang/www.julialang.org/master/blog/_posts/2018-05-11-extensible-broadcast-fusion.md) Matt uses backticks in links:

```
* [`BitArray`s][] can identify cases
...

[`BitArray`s]: https://docs.julialang.org/en/latest/base/arrays/#Base.BitArray
```

which JuDoc doesn't like. It's easier not to support it, perhaps?

2: In [Debuggers](https://raw.githubusercontent.com/JuliaLang/www.julialang.org/master/blog/_posts/2019-03-19-debuggers.md), the reference links are coming through strangely:

```
The debugger is itself a collection of tools that enable those
features. The core is powered by [an interpreter][JI] that can
faithfully run Julia code while allowing various front-ends to control its
execution. Each front-end is its own package: [Juno][] incorporates
the debugger into its IDE, [Rebugger][RB] provides a REPL text UI, and
the traditional step/next/continue command-line interface is provided
by [Debugger][DB]. All these new debugging capabilities seamlessly
integrate with [Revise][RV], so that you can continuously analyze and
modify code in a single session.

...

[CT]: https://github.com/timholy/CodeTracking.jl
[DB]: https://github.com/JuliaDebug/Debugger.jl
[JI]: https://github.com/JuliaDebug/JuliaInterpreter.jl
[LCU]: https://github.com/JuliaDebug/LoweredCodeUtils.jl
[RB]: https://github.com/timholy/Rebugger.jl
[RV]: https://github.com/timholy/Revise.jl
[Juno]: http://junolab.org/
```

<img width="486" alt="Screenshot 2019-10-11 at 08 54 22" src="https://user-images.githubusercontent.com/52289/66634332-bdcf1400-ec04-11e9-8319-3c6f9e345bb2.png">

I'm on `v0.3.4#master`.

**Comment by tlienart** [comment]
<img width="725" alt="Screen Shot 2019-10-11 at 10 53 18" src="https://user-images.githubusercontent.com/10897531/66638523-66856f80-ec15-11e9-9e8f-7b3945053dab.png">

victory for the second one

**Comment by cormullion** [comment]
Awesome!

**Comment by tlienart** [comment]
Well the first issue is fixed too now 👅 

<img width="503" alt="Screen Shot 2019-10-11 at 11 39 25" src="https://user-images.githubusercontent.com/10897531/66641840-d0a11300-ec1b-11e9-8aa2-275909935a40.png">

**Comment by cormullion** [comment]
I'm impressed at your productivity! :)

**Comment by tlienart** [comment]
yeah, I now use JuDoc to write tutorials for MLJ (which is essentially my job atm) so it helps 😄
