### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by cormullion** [cormullion/julialangblog#5]
I noticed that 

```
```TOML
[socrates]
```

was rendered as:

<img width="337" alt="Screenshot 2019-11-21 at 15 54 59" src="https://user-images.githubusercontent.com/52289/69353983-52527a80-0c77-11ea-8f37-72cc9224cf7c.png">

Would it be better to just default to plain text and hide the format?

**Comment by tlienart** [comment]
do you have `@def hascode = true` on that page ?

**Comment by cormullion** [comment]
Yes, it's got that. I thought JuDoc would just think "don't know that language" and ignore it... :)

Are you prepared for the huge increase in demand once you make an announcement? :) I think JuDoc is even listed as a task for Google Code-in, starting soon...

**Comment by tlienart** [comment]
Hahaha thanks 😄  fingers crossed there will be other people willing to help make this cool :)

**Comment by tlienart** [comment]
Hmmm

```julia
julia> s = raw"""
       blah
       ```TOML
       socrates
       ```
       end
       """
"blah\n```TOML\nsocrates\n```\nend\n"

julia> jd2html(s)
"<p>blah <pre><code class=\"plaintext\">TOML\nsocrates</code></pre> end</p>\n"
```

I need to further investigate

**Comment by tlienart** [comment]
ok that's available on master now
